development:
  adapter: redis
  url: <%= "#{ENV.fetch("REDIS_URL")}/1" %>
  channel_prefix: DMandas_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= "#{ENV.fetch("REDIS_URL")}/1" %>
  channel_prefix: DMandas_production
